{% set name = "ib_async" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ib_async-{{ version }}.tar.gz
  sha256: b690c9b00a10827a6c57c005cfe9a2be796ad54bc1a008e6243be9f3fd9d2e00

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - poetry-core
    - pip
  run:
    - python >=3.10
    - eventkit
    - nest-asyncio

test:
  imports:
    - ib_async
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ib-api-reloaded/ib_async
  summary: Python sync/async framework for Interactive Brokers API
  license: BSD-2-Clause
  license_file: LICENSE
  doc_url: https://ib-api-reloaded.github.io/ib_async
  description: |
    The goal of the ib_async library is to make working with the Trader Workstation API
    from Interactive Brokers as easy as possible.

extra:
  recipe-maintainers:
    - sanurielf
