{% set python_min = "3.10" %}
{% set name = "ib_async" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ib_async-{{ version }}.tar.gz
  sha256: 6a03a87d6c06acacb0217a5bea60a8a168ecd5b5a7e86e1c73678d5b48cbc796

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - aeventkit >=2.1.0
    - nest-asyncio
    - python-tzdata >=2025.2

test:
  imports:
    - ib_async
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ib-api-reloaded/ib_async
  summary: Python sync/async framework for Interactive Brokers API
  license: BSD-2-Clause
  license_file: LICENSE
  doc_url: https://ib-api-reloaded.github.io/ib_async
  description: |
    The goal of the ib_async library is to make working with the Trader Workstation API
    from Interactive Brokers as easy as possible.

extra:
  recipe-maintainers:
    - sanurielf
