{% set name = "ib_async" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ib_async-{{ version }}.tar.gz
  sha256: 593691e1a8a1557ac053c601b70bf1527163a517cea3bbfdb2fadfc8a381d15e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - poetry-core
    - pip
  run:
    - python >=3.10
    - eventkit
    - nest-asyncio

test:
  imports:
    - ib_async
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ib-api-reloaded/ib_async
  summary: Python sync/async framework for Interactive Brokers API
  license: BSD-2-Clause
  license_file: LICENSE
  doc_url: https://ib-api-reloaded.github.io/ib_async
  description: |
    The goal of the ib_async library is to make working with the Trader Workstation API
    from Interactive Brokers as easy as possible.

extra:
  recipe-maintainers:
    - sanurielf
